name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11","3.12"]

    runs-on: ${{matrix.runner}}
    name: Test on ${{matrix.runner}} with Python ${{matrix.python-version}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tkinter
      run: |
        if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
          pip install tkinter
        else
          echo "Tkinter is pre-installed on non-Windows systems."
        fi

    - name: Run tests
      run: pytest -svv
